"use client";

import React, { forwardRef } from "react";
import { format, eachDayOfInterval, startOfMonth, endOfMonth, isSameDay, isWeekend } from "date-fns";
import { pl, uk, enUS } from "date-fns/locale";
import { Employee, Shift } from "@/types";
import { useLanguage } from "@/context/language-context";

interface Props {
    date: Date;
    employees: Employee[];
    shifts: Shift[];
}

export const MonthlyPrintView = forwardRef<HTMLDivElement, Props>(({ date, employees, shifts }, ref) => {
    const { language, t } = useLanguage();

    const dateLocale = language === 'uk' ? uk : language === 'pl' ? pl : enUS;

    const daysInMonth = eachDayOfInterval({
        start: startOfMonth(date),
        end: endOfMonth(date),
    });

    return (
        <div ref={ref} className="p-8 bg-white text-black print-container">
            <style type="text/css" media="print">
                {`
                @page { size: landscape; margin: 10mm; }
                body { -webkit-print-color-adjust: exact; }
                .print-container { width: 100%; }
                table { border-collapse: collapse; width: 100%; font-size: 10px; }
                th, td { border: 1px solid #000; padding: 2px; text-align: center; }
                th { background-color: #f0f0f0 !important; }
                .weekend { background-color: #f8f9fa !important; }
                `}
            </style>

            <div className="mb-4 flex justify-between items-end">
                <div>
                    <h1 className="text-2xl font-bold uppercase tracking-wider">
                        {t("schedule")} — {format(date, "MMMM yyyy", { locale: dateLocale })}
                    </h1>
                    <p className="text-sm text-gray-500">Generated by Smart Shift Scheduler</p>
                </div>
                <div className="text-right text-xs">
                    {t("stats.total_shifts")}: {shifts.length}
                </div>
            </div>

            <table className="w-full border border-black text-[10px]">
                <thead>
                <tr>
                    <th className="min-w-[120px] text-left px-2 py-1 font-bold">
                        {t("common.staff")}
                    </th>
                    {daysInMonth.map((day) => (
                        <th
                            key={day.toString()}
                            className={`w-8 ${isWeekend(day) ? "bg-gray-100" : ""}`}
                        >
                            <div className="font-bold">{format(day, "d")}</div>
                            <div className="text-[8px] font-normal uppercase">
                                {format(day, "EEEEEE", { locale: dateLocale })}
                            </div>
                        </th>
                    ))}
                    <th className="w-16 font-bold">Total</th>
                </tr>
                </thead>
                <tbody>
                {employees.map((emp) => {
                    const empShifts = shifts.filter(s => s.employee_id === emp.id);
                    const totalHours = empShifts.reduce((acc, s) => {
                        const start = new Date(s.start_time);
                        const end = new Date(s.end_time);
                        return acc + (end.getTime() - start.getTime()) / (1000 * 60 * 60);
                    }, 0);

                    return (
                        <tr key={emp.id}>
                            <td className="text-left px-2 font-medium whitespace-nowrap">
                                {emp.first_name} {emp.last_name}
                            </td>
                            {daysInMonth.map((day) => {
                                const shift = empShifts.find((s) =>
                                    isSameDay(new Date(s.start_time), day)
                                );

                                return (
                                    <td
                                        key={day.toString()}
                                        className={`${isWeekend(day) ? "bg-gray-50" : ""} h-8`}
                                    >
                                        {shift ? (
                                            <div className="flex flex-col justify-center h-full">
                                                    <span className="font-bold">
                                                        {format(new Date(shift.start_time), "H")}
                                                        -
                                                        {format(new Date(shift.end_time), "H")}
                                                    </span>
                                            </div>
                                        ) : null}
                                    </td>
                                );
                            })}
                            <td className="font-bold bg-gray-50">
                                {Math.round(totalHours)}h
                            </td>
                        </tr>
                    );
                })}
                </tbody>
            </table>

            <div className="mt-8 text-[10px] text-gray-400 flex justify-between border-t pt-2">
                <span>Printed: {format(new Date(), "yyyy-MM-dd HH:mm")}</span>
                <span>Manager Signature: _______________________</span>
            </div>
        </div>
    );
});

MonthlyPrintView.displayName = "MonthlyPrintView";